[2022-04-06 17:29:05,819] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:27:04.827941+00:00 [queued]>
[2022-04-06 17:29:05,832] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:27:04.827941+00:00 [queued]>
[2022-04-06 17:29:05,832] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:29:05,832] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-06 17:29:05,832] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 17:29:05,844] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): sendmail> on 2022-04-06 17:27:04.827941+00:00
[2022-04-06 17:29:05,849] {standard_task_runner.py:52} INFO - Started process 854 to run task
[2022-04-06 17:29:05,851] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_mail', 'sendmail', 'scheduled__2022-04-06T17:27:04.827941+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/send_mail_dag.py', '--cfg-path', '/tmp/tmp4etqnzx2', '--error-file', '/tmp/tmplujqlh41']
[2022-04-06 17:29:05,852] {standard_task_runner.py:80} INFO - Job 13: Subtask sendmail
[2022-04-06 17:29:05,905] {logging_mixin.py:109} INFO - Running <TaskInstance: send_mail.sendmail scheduled__2022-04-06T17:27:04.827941+00:00 [running]> on host 669712b97f52
[2022-04-06 17:29:05,957] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_mail
AIRFLOW_CTX_TASK_ID=sendmail
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T17:27:04.827941+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-06T17:27:04.827941+00:00
[2022-04-06 17:29:08,306] {logging_mixin.py:109} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials t18-20020a639552000000b00381f263db66sm16616426pgn.89 - gsmtp')
[2022-04-06 17:29:08,306] {python.py:175} INFO - Done. Returned value was: None
[2022-04-06 17:29:08,320] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=send_mail, task_id=sendmail, execution_date=20220406T172704, start_date=20220406T172905, end_date=20220406T172908
[2022-04-06 17:29:08,357] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-06 17:29:08,385] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
